ask_dpoponkin/ask/urls.py
from django.conf.urls import url

# import my views
from ask.views import helloWorld

urlpatterns = [
    url(r'^$', helloWorld, name='hello'),
]

ask_dpoponkin/ask_dpoponkin/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^question/', include('questions.urls', namespace='questions')),
    url(r'^ask/', include('ask.urls')),
    url(r'^admin/', admin.site.urls),
]

ask_dpoponkin/questions/urls.py
from django.conf.urls import url

# import my views
from questions.views import *

app_name = 'questions'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^answer/(?P<qid>\d+)/$', answer, name='answer'),
    url(r'^login/$', login, name='login'),
    url(r'^new/$', newQuestion, name='newQuestion'),
    url(r'^signup/$', register, name='register'),
    url(r'^settings/$', settings, name='settings'),
    url(r'^tag/(?P<findTag>\w+)/$', tagged, name='tagged'),
    url(r'^hot/$', hot, name='hot'),
    url(r'^logout/$', logout, name='logout')
]

ask_dpoponkin/questions/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from datetime import datetime

class QuestionManager(models.Manager):
    def all_new(self):
        return self.order_by('-date_pub').all()

    def all_rate(self):
        return self.order_by('-rating').all()

    def all_questions_by_tag(self, tag_name):
        return self.filter(tags__name = tag_name).all()

class AnswerManager(models.Manager):
    def all_answers_by_question(self, question_id):
        return self.filter(question__pk = question_id).all()

class TagManager(models.Manager):
    def get_popular_tags(self):
        return self.all()[:5]

# Create your models here.


class UserImaged(AbstractUser):
    avatar = models.ImageField(upload_to='avatar/%Y/%m/%d/', default='uploads/avatar.jpg')
    rating = models.IntegerField(default=0, verbose_name='Рейтинг')

class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True, verbose_name='Имя категории')
    objects = TagManager()

    def __str__(self):
        return self.name

class Question(models.Model):
    short = models.CharField(max_length=80, verbose_name='Короткий вопрос')
    text = models.TextField(verbose_name='Полный вопрос')
    date_pub = models.DateTimeField(default=datetime.now, verbose_name='Дата публикации')
    author = models.ForeignKey(UserImaged, related_name='qauthor', verbose_name='Автор вопроса')
    tags = models.ManyToManyField(Tag, related_name='qtags', verbose_name='Связанные тэги')
    rating = models.IntegerField(default=0, verbose_name='Рейтинг')
    manager = QuestionManager()

    def __str__(self):
        return self.author.__str__() + " asks " + self.short

class LikeToQuestion(models.Model):
    who = models.ForeignKey(UserImaged, related_name='who_q_likes', verbose_name='Кто лайкнул')
    id_q = models.ForeignKey(Question, related_name='what_q_likes', verbose_name='ID вопроса')
    value = models.IntegerField(default=1, verbose_name='Value')

    def __str__(self):
        ans = str(self.who)
        ans += " likes " + str(self.whom)
        return ans

class Answer(models.Model):
    text = models.TextField(verbose_name='Текст ответа')
    author = models.ForeignKey(UserImaged, related_name='aauthor', verbose_name='Автор ответа')
    date_pub = models.DateTimeField(default=datetime.now, verbose_name='Дата публикации')
    question = models.ForeignKey(Question, related_name='aquestion', verbose_name='Вопрос')
    correct = models.BooleanField(default=False, verbose_name='Верно?')
    rating = models.IntegerField(default=0, verbose_name='Рейтинг')
    manager = AnswerManager()

    def __str__(self):
        return self.author.__str__() + " answers " + self.text


class LikeToAnswer(models.Model):
    who = models.ForeignKey(UserImaged, related_name='who_a_likes', verbose_name='Кто лайкнул')
    id_a = models.ForeignKey(Answer, related_name='what_a_likes', verbose_name='ID ответа')
    value = models.IntegerField(default=1, verbose_name='Value')

    def __str__(self):
        ans = str(self.who)
        ans += " likes " + str(self.whom)
        return ans

ask_dpoponkin/questions/forms.py
from django.http import HttpResponse, Http404
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.core.files import File
from ask.models import *
from questions.models import UserImaged, Question, Tag, Answer
from django import forms

class LoginForm(forms.Form):
    login = forms.CharField(
        label='Login',
        widget=forms.TextInput(attrs={'class': 'w-50', 'placeholder': 'Enter your Username here', }),
        max_length=30
    )
    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={'class': 'w-50', 'placeholder': '*******', }),
        min_length=8
    )

    def clean(self):
        data = self.cleaned_data
        user = authenticate(username=data.get('login', ''), password=data.get('password', ''))

        if user is not None:
            if user.is_active:
                data['user'] = user
            else:
                raise forms.ValidationError('User is not active')
        else:
            raise forms.ValidationError('Wrong login or password')


class SignupForm(forms.Form):
    username = forms.CharField(
        label='Login',
        widget=forms.TextInput(attrs={'placeholder': 'Enter your Username here', }),
        max_length=30
    )
    email = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(attrs={'placeholder': 'example@mail.ru', }),
        max_length=100
    )
    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={'placeholder': '********'}),
        min_length=8
    )
    password_repeat = forms.CharField(
        label='Repeat Password',
        widget=forms.PasswordInput(attrs={'placeholder': '********'}),
        min_length=8
    )
    avatar = forms.FileField(
        label='Avatar',
        widget=forms.ClearableFileInput(),
        required=False
    )

    def clean_username(self):
        username = self.cleaned_data.get('username', '')

        try:
            u = UserImaged.objects.get(username=username)
            raise forms.ValidationError('Username is already used')
        except UserImaged.DoesNotExist:
            return username

    def clean_password_repeat(self):
        pswd = self.cleaned_data.get('password', '')
        pswd_repeat = self.cleaned_data.get('password_repeat', '')

        if pswd != pswd_repeat:
            raise forms.ValidationError('Passwords does not matched')
        return pswd_repeat

    def clean_email(self):
        email = self.cleaned_data.get('email', '')

        try:
            e = UserImaged.objects.get(email=email)
            raise forms.ValidationError('Email is already used')
        except UserImaged.DoesNotExist:
            return email

    def clean_avatar(self):
        avatar = self.cleaned_data.get('avatar')

        if avatar is not None:
            if 'image' not in avatar.content_type:
                raise forms.ValidationError('Wrong image type')
        return avatar

    def save(self):
        data = self.cleaned_data
        password = data.get('password')
        u = UserImaged()

        u.username = data.get('username')
        u.password = make_password(password)
        u.email = data.get('email')
        u.is_active = True
        u.save()

        if data.get('avatar') is not None:
            u.avatar = data.get('avatar')

        u.save()

        return authenticate(username=u.username, password=password)

    def edit(self, user):
        data = self.cleaned_data
        password = data.get('password')
        user.username = data.get('username')
        user.password = make_password(password)
        user.email = data.get('email')
        user.is_active = True
        user.save()

        if data.get('avatar') is not None:
            user.avatar = data.get('avatar')

        user.save()

        return authenticate(username=user.username, password=password)


class QuestionForm(forms.Form):
    short = forms.CharField(
        label='Title',
        widget=forms.TextInput(attrs={'class':'w-75', 'placeholder': 'Enter question title here', }),
        max_length=100
    )
    text = forms.CharField(
        label='Text',
        widget=forms.Textarea(
            attrs={'class': 'w-75', 'rows': '13', 'placeholder': 'Add the question description here', }),
        max_length=100000
    )
    tags = forms.CharField(
        label='Tags',
        widget=forms.TextInput(attrs={'class': 'w-75', 'placeholder': 'Tag1,Tag2,Tag3'}),
        required=False
    )

    def check_tag(self, tag):
        if (' ' in tag) or ('\n' in tag) or ('\t' in tag):
            raise forms.ValidationError('Tags contain spaces')
        if ('/' in tag) or ('\\' in tag) or ('?' in tag):
            raise forms.ValidationError('You can use only this symbols -+_~&@*%$')
        return tag

    def parse_tags(self, tags):
        self._tag_list = tags.split(',', 10)

    def clean_tags(self):
        tags = self.cleaned_data.get('tags', '')
        self.parse_tags(tags)
        for tag in self._tag_list:
            self.check_tag(tag)

    def save(self, user):
        data = self.cleaned_data
        q = Question.manager.create(short=data.get('short'), text=data.get('text'),
                                        author=user)
        q.tags.clear()
        q.save()
        for tag_text in self._tag_list:
            if tag_text is not None and tag_text != '':
                tag = Tag.objects.get_or_create(name=tag_text)
                q.tags.add(tag[0])
        q.save()
        return q


class AnswerForm(forms.Form):
    text = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'w-100', 'rows': '5',
                                     'placeholder': 'Do you know the solution?', })
    )

    def save(self, question, user):
        data = self.cleaned_data
        answer = Answer(text=data.get('text'), author=user, question=question)
        answer.save()
        return answer

ask_dpoponkin/questions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect
from django.contrib import auth
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from questions.forms import LoginForm, SignupForm, QuestionForm, AnswerForm


from questions.models import Question, Answer, Tag, UserImaged

# Create your views here.

#temporary script for generating fields
#import fake
#fake.fakeanswer()

def index(request):

    #from DB!!! 4DZ
    topQuestions = Question.manager.all_new()
    topQuestions = paginate(topQuestions, request, 5)

    topMembers = UserImaged.objects.order_by('-rating').all()[:5]

    topTags = Tag.objects.get_popular_tags()

    context = {'topQuestions': topQuestions, 'topMembers': topMembers, 'topTags': topTags}
    return render(request, 'index/XIndex.html', context)



def answer(request, qid):

    #fromDB!!! 4DZ
    mainQuestion = Question.manager.get(pk = int(qid))

    userAnswers = Answer.manager.all_answers_by_question(qid)

    userAnswers = paginate(userAnswers, request, 5)

    if request.method == "POST":
        form = AnswerForm(request.POST)

        if form.is_valid():
            answer = form.save(mainQuestion, request.user)
            return HttpResponseRedirect(reverse('questions:answer', kwargs={'qid': mainQuestion.pk}))
    else:
        form = AnswerForm()

    topMembers = UserImaged.objects.order_by('-rating').all()[:5]

    topTags = Tag.objects.get_popular_tags()

    context = {'form':form, 'mainQuestion':mainQuestion, 'userAnswers':userAnswers, 'topMembers': topMembers, 'topTags': topTags}
    return render(request, 'answer/answer.html', context)

def login(request):
    redirect = request.GET.get('continue', reverse('questions:index'))

    if request.user.is_authenticated():
        return HttpResponseRedirect(redirect)

    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            auth.login(request, form.cleaned_data['user'])
            return HttpResponseRedirect(redirect)
    else:
        form = LoginForm()

    topMembers = UserImaged.objects.order_by('-rating').all()[:5]

    topTags = Tag.objects.get_popular_tags()

    context = {'topMembers': topMembers, 'topTags': topTags, 'form': form}
    return render(request, 'login/login.html', context)

@login_required(redirect_field_name='continue')
def logout(request):
	redirect = request.GET.get('continue', reverse('questions:index'))
	auth.logout(request)
	return HttpResponseRedirect(redirect)

@login_required(redirect_field_name='continue')
def newQuestion(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            q = form.save(request.user)
            return HttpResponseRedirect(reverse('questions:answer', kwargs={'qid': q.id}))
    else:
        form = QuestionForm()

    topMembers = UserImaged.objects.order_by('-rating').all()[:5]

    topTags = Tag.objects.get_popular_tags()

    context = {'form':form,'topMembers': topMembers, 'topTags': topTags}
    return render(request, 'question/question.html', context)

def register(request):

    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('questions:index'))
    if request.method == "POST":
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            auth.login(request, user)
            return HttpResponseRedirect(reverse('questions:login'))
    else:
        form = SignupForm()

    topMembers = UserImaged.objects.order_by('-rating').all()[:5]

    topTags = Tag.objects.get_popular_tags()

    context = {'topMembers': topMembers, 'topTags': topTags, 'form':form}
    return render(request, 'register/register.html', context)

@login_required(redirect_field_name='continue')
def settings(request):

    if request.method == "POST":
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.edit(request.user)
            return HttpResponseRedirect(reverse('questions:settings'))
    else:
        form = SignupForm()

    topMembers = UserImaged.objects.order_by('-rating').all()[:5]

    topTags = Tag.objects.get_popular_tags()

    context = {'form': form, 'topMembers': topMembers, 'topTags': topTags}
    return render(request, 'settings/settings.html', context)

def tagged(request, findTag):

    #from DB!!! 4DZ
    topQuestions = Question.manager.all_questions_by_tag(findTag)
    topQuestions = paginate(topQuestions, request, 5)

    topMembers = UserImaged.objects.order_by('-rating').all()[:5]

    topTags = Tag.objects.get_popular_tags()

    context = {'findTag':findTag, 'topQuestions': topQuestions, 'topMembers': topMembers, 'topTags': topTags}
    return render(request, 'tagged/tagged.html', context)

def hot(request):

    #from DB!!! 4DZ
    topQuestions = Question.manager.all_rate()
    topQuestionsP = paginate(topQuestions, request, 5)

    topMembers = UserImaged.objects.order_by('-rating').all()[:5]

    topTags = Tag.objects.get_popular_tags()

    context = {'topQuestionsP': topQuestionsP, 'topMembers': topMembers, 'topTags': topTags}
    return render(request, 'hot/hot.html', context)

def paginate(objects_list, request, count):
    paginator = Paginator(objects_list, count)
    page = request.GET.get('page')
    try:
        topQuestions = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        topQuestions = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        topQuestions = paginator.page(paginator.num_pages)

    return topQuestions

ask_dpoponkin/questions/templates/answer/answer.html
{% extends "index.html" %}

{% block content %}
    {% block topic %}
        <div class="row">
            <h1 class="col-8">Q&amp;A</h1>
          <!--<h4 class="col-4">Hot questions</h4>-->
        </div><!--/span-->
    <hr>
    {% endblock topic %}
    <div class="margin-good border border-left-0 border-right-0 border-top-0">
		{% block mainQuestion %}
			{%include "answer/mainQuestion.html" %}
		{% endblock mainQuestion %}
		<br>
		<div class="row">
			<div class="col-1">
			</div>
			<div class="col-11">
				{% block answers %}
					{% for userAnswer in userAnswers %}
						{% include "answer/userAnswer.html" %}
					{% endfor %}
				{% endblock answers %}

				{% block yourAnswer %}
					{% include "answer/yourAnswer.html" %}
				{% endblock yourAnswer %}
			</div>
		</div>
    </div>
{% endblock content %}

{% block paginator %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-start">
        {% if userAnswers.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ userAnswers.previous_page_number }}">Previous</a>
            </li>
        {% else %}
            <li class="page-item disabled ">
                <a class="page-link" href="">Previous</a>
            </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">{{ userAnswers.number }}</a>
        </li>
        {% if userAnswers.has_next %}
            <li class="page-item  ">
                <a class="page-link" href="?page={{ userAnswers.next_page_number }}">Next</a>
            </li>
        {% else %}
            <li class="page-item disabled ">
                <a class="page-link" href="">Next</a>
            </li>
        {% endif %}
    </ul>
</nav>
{% endblock paginator %}

ask_dpoponkin/questions/templates/answer/mainQuestion.html
<div class="row border border-left-0 border-right-0 border-top-0">
    <div class="col-2">
        <div class="center-image">
            <img class="userpic80" src="http://placehold.it/400x200"/>
        </div>
        <div class="rating-bar">
            <div class="row justify-content-start">
                <div class="col-3 minus-button">
                    <a class="nomargin nopadding" href="#" role="button">
                        <div class="minus-button">
                            <p>-</p>
                        </div>
                    </a>
                </div>
                <div class="col-6 rating-value nomargin nopadding">
                    <p class="">{{ mainQuestion.rating }}</p>
                </div>
                <div class="col-3 plus-button">
                    <a class="nomargin nopadding" href="#" role="button">
                        <div class="plus-button">
                            <p>+</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-10">
        <h2>{{ mainQuestion.short }}</h2>
        <p>{{ mainQuestion.text }}</p>
        <div class="row">
            <div class="col-4">
            </div>
            <div class="col-8">
                <p class="tag">Tags:
					{% for tag in mainQuestion.tags.all %}
						<a href="{% url 'questions:tagged' tag.name %}">{{ tag.name }}</a>
					{% endfor %}
				</p>
            </div>
        </div>
    </div>
</div><!--/span-->

ask_dpoponkin/questions/templates/answer/userAnswer.html
<div class="row">
    <div class="col-2">
        <div class="center-image">
            <img class="userpic60" src="http://placehold.it/400x200"/>
        </div>
        <div class="rating-bar">
            <div class="row justify-content-start">
                <div class="col-3 minus-button">
                    <a class="nomargin nopadding" href="#" role="button">
                        <div class="minus-button">
                            <p>-</p>
                        </div>
                    </a>
                </div>
                <div class="col-6 rating-value nomargin nopadding">
                    <p class="">{{ userAnswer.rating }}</p>
                </div>
                <div class="col-3 plus-button">
                    <a class="nomargin nopadding" href="#" role="button">
                        <div class="plus-button">
                            <p>+</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-10">
        <p>{{ userAnswer.text }}</p>
        <p>
            <a class="btn btn-outline-success" href="#" role="button">
                <input class="m-0" type="checkbox" id="coding{{ userAnswer.pk }}" name="interest" value="coding">
                <label class="m-0" for="coding{{ userAnswer.pk }}">Correct</label>
            </a>
        </p>
    </div>
</div><!--/span-->

ask_dpoponkin/questions/templates/answer/yourAnswer.html
{% for error in form.non_field_errors %}
    <p class="alert text-center">{{ error }}</p>
{% endfor %}
<hr>
<form action="#" method="POST">
    {% csrf_token %}

    <div class="row">
        {% for f in form.visible_fields %}
        <div class="col-2">
            <p>{{ f.label }}</p>
        </div>
        <div class="col-10">
            {{ f }}
        </div>
        {% endfor %}
    </div>

    <br>
    <p class="text-right w-100"><input class="btn btn-outline-success" type="submit" value="Post answer"></p>
</form>